Repository david-shortman/netflix-party-plus, pull requests merged in 2020-04, with the labels that each got.

#12 Create classes for outgoing messages
  flutter_app/lib/MessageArray.dart
  flutter_app/lib/MessageObject.dart
  flutter_app/lib/MessageSendMessage.dart
  flutter_app/lib/MessageServerTime.dart
  flutter_app/lib/MessageSid.dart
  flutter_app/lib/MessageUpdate.dart
  flutter_app/lib/MessageUserId.dart
  flutter_app/lib/MessageUtility.dart
  flutter_app/lib/MessageVideoIdAndMessageBacklog.dart
  flutter_app/lib/ReceivedMessage.dart
  flutter_app/lib/domains/mappable/Mappable.dart
  flutter_app/lib/domains/messages/Message.dart
  flutter_app/lib/domains/messages/MessageContent.dart
  flutter_app/lib/domains/messages/buffering/BufferingContent.dart
  flutter_app/lib/domains/messages/buffering/BufferingMessage.dart
  flutter_app/lib/domains/messages/chat-message/SendMessageBody.dart
  flutter_app/lib/domains/messages/chat-message/SendMessageContent.dart
  flutter_app/lib/domains/messages/chat-message/SendMessageMessage.dart
  flutter_app/lib/domains/messages/join-session/JoinSessionContent.dart
  flutter_app/lib/domains/messages/join-session/JoinSessionMessage.dart
  flutter_app/lib/domains/messages/join-session/UserSettings.dart
  flutter_app/lib/domains/messages/server-time/GetServerTimeContent.dart
  flutter_app/lib/domains/messages/server-time/GetServerTimeMessage.dart
  flutter_app/lib/domains/messages/update-session/UpdateSessionContent.dart
  flutter_app/lib/domains/messages/update-session/UpdateSessionMessage.dart
  flutter_app/lib/domains/messenger/Messenger.dart
  flutter_app/lib/main.dart
  flutter_app/pubspec.lock
  flutter_app/pubspec.yaml
  flutter_app/test/domains/messenger/messenger_test.dart
Labels: tech debt

#14 Move sequence generation to Messenger
  flutter_app/lib/domains/messenger/Messenger.dart
  flutter_app/lib/main.dart
  flutter_app/test/domains/messenger/messenger_test.dart
Labels: tech debt

#28 Updated interface and cleaned up code organization
  flutter_app/lib/main.dart
  flutter_app/pubspec.lock
  flutter_app/pubspec.yaml
Labels: enhancement

#35 Added barcode scanning feature
  flutter_app/ios/Podfile.lock
  flutter_app/ios/Runner/Info.plist
  flutter_app/lib/main.dart
  flutter_app/pubspec.lock
  flutter_app/pubspec.yaml
Labels: enhancement

#36 Fixed catchup message processing
  flutter_app/lib/domains/messages/incoming-messages/ReceivedMessageUtility.dart
Labels: bug

#55 Dark mode, chat enhancements
  flutter_app/assets/avatars/SailorCat.svg
  flutter_app/ios/Runner/Base.lproj/LaunchScreen.storyboard
  flutter_app/lib/domains/avatar/Avatar.dart
  flutter_app/lib/domains/messages/incoming-messages/ReceivedMessageUtility.dart
  flutter_app/lib/domains/messages/incoming-messages/UserMessage.dart
  flutter_app/lib/domains/messages/outgoing-messages/join-session/UserSettings.dart
  flutter_app/lib/main.dart
  flutter_app/lib/pages/UserSettingsScreen.dart
  flutter_app/lib/theming/AppTheme.dart
  flutter_app/lib/theming/UserColors.dart
  flutter_app/lib/widgets/ChatStream.dart
Labels: enhancement, feature, user experience

#56 Automated deploys
  .gitignore
  flutter_app/ios/Gemfile
  flutter_app/ios/fastlane/Appfile
  flutter_app/ios/fastlane/Fastfile
  flutter_app/ios/fastlane/Matchfile
  flutter_app/ios/fastlane/README.md
  flutter_app/pubspec.yaml
Labels: pipeline

#60 Updated styling to incorporate cupertino elements
  flutter_app/ios/Runner/Info.plist
  flutter_app/lib/main.dart
  flutter_app/lib/pages/UserSettingsScreen.dart
  flutter_app/lib/theming/AppTheme.dart
  flutter_app/lib/widgets/ChatStream.dart
  flutter_app/lib/widgets/MainPage.dart
Labels: user experience

#61 Update to xcode 11.4
  flutter_app/ios/Podfile.lock
  flutter_app/ios/Runner.xcodeproj/project.pbxproj
  flutter_app/ios/Runner.xcworkspace/contents.xcworkspacedata
Labels: pipeline

#62 Added someone is typing message
  flutter_app/lib/domains/messages/incoming-messages/ReceivedMessageUtility.dart
  flutter_app/lib/domains/messages/incoming-messages/SetPresenceMessage.dart
  flutter_app/lib/domains/messages/outgoing-messages/typing/TypingContent.dart
  flutter_app/lib/domains/messages/outgoing-messages/typing/TypingMessage.dart
  flutter_app/lib/domains/messenger/Messenger.dart
  flutter_app/lib/main.dart
  flutter_app/lib/pages/MainPage.dart
  flutter_app/lib/widgets/ChatStream.dart
Labels: feature

#77 Light mode support for changelog and panel
  flutter_app/lib/pages/MainPage.dart
  flutter_app/lib/theming/AppTheme.dart
  flutter_app/lib/widgets/ChangelogDialogFactory.dart
Labels: bug

#82 Copied files
  chrome/netflix-party-harder/README 2.md
  chrome/netflix-party-harder/README.md
  chrome/netflix-party-harder/_locales/en/messages.json
  chrome/netflix-party-harder/background.js
  chrome/netflix-party-harder/content_script.js
  chrome/netflix-party-harder/icon.png
  chrome/netflix-party-harder/iconx300.png
  chrome/netflix-party-harder/img/Alien.svg
  chrome/netflix-party-harder/img/Batman.svg
  chrome/netflix-party-harder/img/ChickenLeg.svg
  chrome/netflix-party-harder/img/Chocobar.svg
  chrome/netflix-party-harder/img/Cinderella.svg
  chrome/netflix-party-harder/img/Cookie.svg
  chrome/netflix-party-harder/img/CptAmerica.svg
  chrome/netflix-party-harder/img/DeadPool.svg
  chrome/netflix-party-harder/img/Exit-Unhover.svg
  chrome/netflix-party-harder/img/Goofy.svg
  chrome/netflix-party-harder/img/Hamburger.svg
  chrome/netflix-party-harder/img/IceCream.svg
  chrome/netflix-party-harder/img/IronMan.svg
  chrome/netflix-party-harder/img/Link.svg
  chrome/netflix-party-harder/img/Mulan.svg
  chrome/netflix-party-harder/img/Pizza.svg
  chrome/netflix-party-harder/img/Poohbear.svg
  chrome/netflix-party-harder/img/Popcorn.svg
  chrome/netflix-party-harder/img/Sailor Cat.svg
  chrome/netflix-party-harder/img/Sailormoon.svg
  chrome/netflix-party-harder/img/Snow-White.svg
  chrome/netflix-party-harder/img/Wolverine.svg
  chrome/netflix-party-harder/img/edit.svg
  chrome/netflix-party-harder/img/hide.svg
  chrome/netflix-party-harder/img/hidebtn.svg
  chrome/netflix-party-harder/img/hotdog.svg
  chrome/netflix-party-harder/img/refresh.svg
  chrome/netflix-party-harder/jquery.js
  chrome/netflix-party-harder/manifest.json
  chrome/netflix-party-harder/normalize.css
  chrome/netflix-party-harder/old_content_script.js
  chrome/netflix-party-harder/popup.css
  chrome/netflix-party-harder/popup.html
  chrome/netflix-party-harder/popup.js
Labels: enhancement, feature, user experience

#83 New features
  chrome/netflix-party-harder/content_script.js
  chrome/netflix-party-harder/popup.html
  chrome/netflix-party-harder/popup.js
Labels: enhancement, feature, user experience

#87 Updates for 1.0.0 release
  flutter_app/android/app/build.gradle
  flutter_app/android/app/src/debug/AndroidManifest.xml
  flutter_app/android/app/src/main/AndroidManifest.xml
  flutter_app/android/app/src/main/kotlin/com/jrlambs/flutterapp/MainActivity.kt
  flutter_app/android/app/src/profile/AndroidManifest.xml
  flutter_app/lib/domains/avatar/Avatar.dart
  flutter_app/lib/domains/messages/MessageArray.dart
  flutter_app/lib/domains/messages/MessageContent.dart
  flutter_app/lib/domains/messages/SocketMessage.dart
  flutter_app/lib/domains/messages/incoming-messages/ArrayMessage.dart
  flutter_app/lib/domains/messages/incoming-messages/ObjectMessage.dart
  flutter_app/lib/domains/messages/incoming-messages/ReceivedMessageUtility.dart
  flutter_app/lib/domains/messages/incoming-messages/SentMessageMessage.dart
  flutter_app/lib/domains/messages/incoming-messages/ServerTimeMessage.dart
  flutter_app/lib/domains/messages/incoming-messages/SetPresenceMessage.dart
  flutter_app/lib/domains/messages/incoming-messages/SidMessage.dart
  flutter_app/lib/domains/messages/incoming-messages/UserIdMessage.dart
  flutter_app/lib/domains/messages/incoming-messages/VideoIdAndMessageCatchupMessage.dart
  flutter_app/lib/domains/messages/outgoing-messages/broadcast-user-settings/BroadcastUserSettingsContent.dart
  flutter_app/lib/domains/messages/outgoing-messages/buffering/BufferingContent.dart
  flutter_app/lib/domains/messages/outgoing-messages/buffering/BufferingMessage.dart
  flutter_app/lib/domains/messages/outgoing-messages/chat-message/SendMessageBody.dart
  flutter_app/lib/domains/messages/outgoing-messages/chat-message/SendMessageContent.dart
  flutter_app/lib/domains/messages/outgoing-messages/chat-message/SendMessageMessage.dart
  flutter_app/lib/domains/messages/outgoing-messages/dynamic/DynamicMessageContent.dart
  flutter_app/lib/domains/messages/outgoing-messages/dynamic/SingleValueDynamicMessageContent.dart
  flutter_app/lib/domains/messages/outgoing-messages/empty-message/EmptyMessage.dart
  flutter_app/lib/domains/messages/outgoing-messages/join-session/JoinSessionContent.dart
  flutter_app/lib/domains/messages/outgoing-messages/join-session/JoinSessionMessage.dart
  flutter_app/lib/domains/messages/outgoing-messages/join-session/UserSettings.dart
  flutter_app/lib/domains/messages/outgoing-messages/server-time/GetServerTimeContent.dart
  flutter_app/lib/domains/messages/outgoing-messages/server-time/GetServerTimeMessage.dart
  flutter_app/lib/domains/messages/outgoing-messages/typing/TypingContent.dart
  flutter_app/lib/domains/messages/outgoing-messages/update-session/UpdateSessionContent.dart
  flutter_app/lib/domains/messages/outgoing-messages/update-session/UpdateSessionMessage.dart
  flutter_app/lib/domains/messenger/Messenger.dart
  flutter_app/lib/main.dart
  flutter_app/lib/pages/MainPage.dart
  flutter_app/lib/theming/AvatarColors.dart
  flutter_app/lib/widgets/ChangelogDialogFactory.dart
  flutter_app/lib/widgets/ChatStream.dart
  flutter_app/pubspec.yaml
  flutter_app/test/domains/messenger/Messenger_test.dart
Labels: enhancement, user experience

#98 Fixed session loop bug and updated changelog
  flutter_app/lib/changelog/ChangelogService.dart
  flutter_app/lib/pages/AppContainer.dart
  flutter_app/lib/pages/ChatFeedPage.dart
  flutter_app/lib/theming/AppTheme.dart
Labels: bug

#100 Added forward/backward 10 seconds buttons
  flutter_app/lib/changelog/ChangelogService.dart
  flutter_app/lib/domains/server/ServerInfo.dart
  flutter_app/lib/pages/AppContainer.dart
  flutter_app/lib/pages/ChatFeedPage.dart
  flutter_app/lib/services/PartyService.dart
  flutter_app/lib/services/SocketMessengerService.dart
  flutter_app/lib/store/PlaybackInfoStore.dart
  flutter_app/lib/widgets/ControlPanel.dart
  flutter_app/pubspec.lock
  flutter_app/pubspec.yaml
Labels: bug

#101 Seekbar and then some
  flutter_app/ios/Runner/Info.plist
  flutter_app/lib/domains/messages/incoming-messages/VideoIdAndMessageCatchupMessage.dart
  flutter_app/lib/domains/playback/PlaybackInfo.dart
  flutter_app/lib/domains/server/ServerInfo.dart
  flutter_app/lib/domains/video/VideoInfo.dart
  flutter_app/lib/pages/AppContainer.dart
  flutter_app/lib/pages/ChatFeedPage.dart
  flutter_app/lib/pages/LandingPage.dart
  flutter_app/lib/services/LocalUserService.dart
  flutter_app/lib/services/PartyService.dart
  flutter_app/lib/services/SocketMessengerService.dart
  flutter_app/lib/services/SomeoneIsTypingService.dart
  flutter_app/lib/store/ChatMessagesStore.dart
  flutter_app/lib/store/PartySessionStore.dart
  flutter_app/lib/theming/AppTheme.dart
  flutter_app/lib/vaults/LabelVault.dart
  flutter_app/lib/widgets/ControlPanel.dart
  flutter_app/pubspec.lock
  flutter_app/pubspec.yaml
Labels: effort-level-medium, enhancement, feature

#102 Prepare extension for publish
  chrome/netflix-party-harder/README 2.md
  chrome/netflix-party-harder/README.md
  chrome/netflix-party-harder/_locales/en/messages.json
  chrome/netflix-party-harder/background.js
  chrome/netflix-party-harder/content_script.js
  chrome/netflix-party-harder/icon.png
  chrome/netflix-party-harder/iconx300.png
  chrome/netflix-party-harder/manifest.json
  chrome/netflix-party-harder/popup.html
  chrome/netflix-party-harder/popup.js
Labels: effort-level-medium, enhancement
